# Change these first
owner: Loapu # Your GitHub organization or username, where this repository lives
repo: status.loapu.dev # The name of this repository

sites:
  - name: Homepage
    url: https://loapu.dev
  - name: Documentation
    url: https://docs.loapu.dev
    
assignees:
  - Loapu

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.loapu.dev
  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/7953031?s=256&v=4
  name: Loapu Status Page
  theme: night
  introTitle: "Welcome to my private status page"
  introMessage: The sites listed here are either made or at least managed by me.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
